# Generated by Django 5.2.9 on 2026-01-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_metafinanceira'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('outros', 'Outros')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita (Entrada)'), ('despesa', 'Despesa (Saída)')], default='despesa', max_length=10),
        ),
    ]
